/*
 * qspi.h
 *
 *  Created on: Nov 10, 2025
 *      Author: steve
 */

#ifndef INC_QSPI_H_
#define INC_QSPI_H_

#include "stm32h7xx_hal.h"   // or your family header
#include <string.h>
#include <stdio.h>


extern QSPI_HandleTypeDef hqspi; // generated by CubeMX

// --- Micron MT25QL512 Core Opcodes (single I/O) ---
#define CMD_READ_ID                 0x9F
#define CMD_READ_STATUS_REG         0x05
#define CMD_WRITE_ENABLE            0x06
#define CMD_READ_DATA_3B            0x03
#define CMD_READ_DATA_4B            0x13
#define CMD_PAGE_PROGRAM_3B         0x02
#define CMD_PAGE_PROGRAM_4B         0x12
#define CMD_SUBSECTOR_ERASE_4K_3B   0x20
#define CMD_SUBSECTOR_ERASE_4K_4B   0x21
#define CMD_SECTOR_ERASE_64K_3B     0xD8
#define CMD_SECTOR_ERASE_64K_4B     0xDC
#define CMD_ENABLE_4BYTE_ADDR       0xB7
#define CMD_RESET_ENABLE            0x66
#define CMD_RESET_MEMORY            0x99

// Status Register bits
#define SR_WIP_MASK                 0x01
#define SR_WEL_MASK                 0x02

// Test parameters
#define TEST_ADDR                   0x00010000UL   // any aligned address in device
#define TEST_PAGE_SIZE              256
#define TEST_SUBSECTOR_SIZE         4096
#define QSPI_TIMEOUT                1000

static HAL_StatusTypeDef QSPI_SendSimple(uint8_t instruction);
static HAL_StatusTypeDef QSPI_WriteEnable(void);
static HAL_StatusTypeDef QSPI_WaitWhileBusy(uint32_t timeout_ms);
static HAL_StatusTypeDef QSPI_ReadID(uint8_t id[3]);
static HAL_StatusTypeDef QSPI_Enable4ByteAddressing(void);
static HAL_StatusTypeDef QSPI_Erase4K_4B(uint32_t addr);
static HAL_StatusTypeDef QSPI_PageProgram_4B(uint32_t addr, const uint8_t *data, uint32_t size);
static HAL_StatusTypeDef QSPI_Read_4B(uint32_t addr, uint8_t *data, uint32_t size);







#endif /* INC_QSPI_H_ */
